-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
INNER JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
INNER JOIN ITEM_INFO P ON P.ITEM_ID = T.PARENT_ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY I.ITEM_ID DESC