-- 코드를 작성해주세요
SELECT SUM(GRADE.SCORE) AS SCORE, EMP.EMP_NO, EMP.EMP_NAME, EMP.POSITION, EMP.EMAIL
FROM HR_EMPLOYEES AS EMP
INNER JOIN HR_GRADE AS GRADE ON EMP.EMP_NO = GRADE.EMP_NO
GROUP BY GRADE.EMP_NO
ORDER BY SCORE DESC
LIMIT 1